using System.Resources;
// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//

namespace Microsoft.Practices.EnterpriseLibrary.Data.DB2
{
    internal class SR
    {
        public static string ErrorMessageUpdateDataSetRowFailure
        {
            get { return Keys.GetString(Keys.ErrorMessageUpdateDataSetRowFailure); }
        }

        public static string ErrorMessageParameterMatchFailure
        {
            get { return Keys.GetString(Keys.ErrorMessageParameterMatchFailure); }
        }

        public static string UninitializedString
        {
            get { return Keys.GetString(Keys.UninitializedString); }
        }

        internal class Keys
        {
            private static ResourceManager resourceManager =
                new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Data.DB2.SR", typeof(SR).Module.Assembly);

            public static string GetString(string key)
            {
                return resourceManager.GetString(key, Resources.CultureInfo);
            }

            public static string GetString(string key, params object[] args)
            {
                string msg = resourceManager.GetString(key, Resources.CultureInfo);
                msg = string.Format(msg, args);
                return msg;
            }

            public const string ErrorMessageUpdateDataSetRowFailure = "ErrorMessageUpdateDataSetRowFailure";
            public const string ErrorMessageParameterMatchFailure = "ErrorMessageParameterMatchFailure";
            public const string UninitializedString = "UninitializedString";
        }

    }
}