// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Security.AzMan.Configuration.Design
{
	using System;
	using System.Resources;
	using System.Globalization;

	internal class SR
	{
		public static string AzManProvider
		{
			get { return Keys.GetString( Keys.AzManProvider ); }
		}
		public static string ApplicationDescription
		{
			get { return Keys.GetString( Keys.ApplicationDescription ); }
		}
		public static string AuditIdentiferPrefixDescription
		{
			get { return Keys.GetString( Keys.AuditIdentiferPrefixDescription ); }
		}
		public static string ScopeDescription
		{
			get { return Keys.GetString( Keys.ScopeDescription ); }
		}
		public static string StoreLocationDescription
		{
			get { return Keys.GetString( Keys.StoreLocationDescription ); }
		}
		public static string AuditIdentifierPrefixDescription
		{
			get { return Keys.GetString( Keys.AuditIdentifierPrefixDescription ); }
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.AzMan.Configuration.Design.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Security.AzMan.Configuration.Design.SR).Module.Assembly );

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, Resources.CultureInfo );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, Resources.CultureInfo );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string AzManProvider = "AzManProvider";
			public const string ApplicationDescription = "ApplicationDescription";
			public const string AuditIdentiferPrefixDescription = "AuditIdentiferPrefixDescription";
			public const string ScopeDescription = "ScopeDescription";
			public const string StoreLocationDescription = "StoreLocationDescription";
			public const string AuditIdentifierPrefixDescription = "AuditIdentifierPrefixDescription";
		}


	}
}
