using System.Resources;
// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//

namespace Microsoft.Practices.EnterpriseLibrary.Security.AzMan
{
    internal class SR
    {
        public static string InvalidArgument(string argumentName, string typeName)
        {
            return Keys.GetString(Keys.InvalidArgument, argumentName, typeName);
        }

        public static string NoOperations
        {
            get { return Keys.GetString(Keys.NoOperations); }
        }

        public static string WindowsIdentityOnly
        {
            get { return Keys.GetString(Keys.WindowsIdentityOnly); }
        }

        internal class Keys
        {
            private static ResourceManager resourceManager =
                new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.AzMan.SR", typeof(SR).Module.Assembly);

            public static string GetString(string key)
            {
                return resourceManager.GetString(key, Resources.CultureInfo);
            }

            public static string GetString(string key, params object[] args)
            {
                string msg = resourceManager.GetString(key, Resources.CultureInfo);
                msg = string.Format(msg, args);
                return msg;
            }

            public const string InvalidArgument = "InvalidArgument";
            public const string NoOperations = "NoOperations";
            public const string WindowsIdentityOnly = "WindowsIdentityOnly";
        }

    }
}