// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Security.Database.Authentication.Configuration.Design
{
	using System;
	using System.Resources;
	using System.Globalization;

	internal class SR
	{
		public static CultureInfo Culture
		{
			get
			{
				return Keys.Culture;
			}
			set
			{
				Keys.Culture = value;
			}
		}

		public static string DbAuthenticationProviderHashProviderPropertyDescription
		{
			get { return Keys.GetString( Keys.DbAuthenticationProviderHashProviderPropertyDescription ); }
		}
		public static string DbAuthenticationProviderDatabasePropertyDescription
		{
			get { return Keys.GetString( Keys.DbAuthenticationProviderDatabasePropertyDescription ); }
		}
		public static string DbAuthenticationProviderDisplayName
		{
			get { return Keys.GetString( Keys.DbAuthenticationProviderDisplayName ); }
		}
		public static string DbAuthenticationProvider
		{
			get { return Keys.GetString( Keys.DbAuthenticationProvider ); }
		}
		public static string CategoryGeneral
		{
			get { return Keys.GetString( Keys.CategoryGeneral ); }
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.Database.Authentication.Configuration.Design.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Security.Database.Authentication.Configuration.Design.SR).Module.Assembly );

			static CultureInfo culture = null;

			public static CultureInfo Culture
			{
				get
				{
					return culture;
				}
				set
				{
					culture = value;
				}
			}

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, culture );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, culture );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string DbAuthenticationProviderHashProviderPropertyDescription = "DbAuthenticationProviderHashProviderPropertyDescription";
			public const string DbAuthenticationProviderDatabasePropertyDescription = "DbAuthenticationProviderDatabasePropertyDescription";
			public const string DbAuthenticationProviderDisplayName = "DbAuthenticationProviderDisplayName";
			public const string DbAuthenticationProvider = "DbAuthenticationProvider";
			public const string CategoryGeneral = "CategoryGeneral";
		}


	}
}
