// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Logging.Sinks.Database.Configuration.Design
{
	using System;
	using System.Resources;
	using System.Globalization;

	internal class SR
	{
		public static string DatabaseSink
		{
			get { return Keys.GetString( Keys.DatabaseSink ); }
		}
		public static string StoredProcNameDescription
		{
			get { return Keys.GetString( Keys.StoredProcNameDescription ); }
		}
		public static string CategoryGeneral
		{
			get { return Keys.GetString( Keys.CategoryGeneral ); }
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Logging.Sinks.Database.Configuration.Design.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Logging.Sinks.Database.Configuration.Design.SR).Module.Assembly );

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, Resources.CultureInfo );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, Resources.CultureInfo );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string DatabaseSink = "DatabaseSink";
			public const string StoredProcNameDescription = "StoredProcNameDescription";
			public const string CategoryGeneral = "CategoryGeneral";
		}


	}
}
