// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Logging.Sinks.Database
{
	using System;
	using System.Resources;
	using System.Globalization;

	internal class SR
	{
		public static string DatabaseSinkMissingParameters
		{
			get { return Keys.GetString( Keys.DatabaseSinkMissingParameters ); }
		}
		public static string SinkFailure (string exceptionString)
		{
			return Keys.GetString( Keys.SinkFailure, exceptionString );
		}
		public static string UnknownError
		{
			get { return Keys.GetString( Keys.UnknownError ); }
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Logging.Sinks.Database.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Logging.Sinks.Database.SR).Module.Assembly );

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, Resources.CultureInfo );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, Resources.CultureInfo );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string DatabaseSinkMissingParameters = "DatabaseSinkMissingParameters";
			public const string SinkFailure = "SinkFailure";
			public const string UnknownError = "UnknownError";
		}


	}
}
