// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Caching.Database.Configuration.Design
{
	using System;
	using System.Resources;
	using System.Globalization;

	internal class SR
	{
		public static string DataCacheStorage
		{
			get { return Keys.GetString( Keys.DataCacheStorage ); }
		}
		public static string DatabaseInstanceNameDescription
		{
			get { return Keys.GetString( Keys.DatabaseInstanceNameDescription ); }
		}
		public static string DatabasePartitionNameDesciption
		{
			get { return Keys.GetString( Keys.DatabasePartitionNameDesciption ); }
		}
		public static string CategoryGeneral
		{
			get { return Keys.GetString( Keys.CategoryGeneral ); }
		}
		public static string GenericCreateStatusText (string name)
		{
			return Keys.GetString( Keys.GenericCreateStatusText, name );
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Caching.Database.Configuration.Design.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Caching.Database.Configuration.Design.SR).Module.Assembly );

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, Resources.CultureInfo );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, Resources.CultureInfo );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string DataCacheStorage = "DataCacheStorage";
			public const string DatabaseInstanceNameDescription = "DatabaseInstanceNameDescription";
			public const string DatabasePartitionNameDesciption = "DatabasePartitionNameDesciption";
			public const string CategoryGeneral = "CategoryGeneral";
			public const string GenericCreateStatusText = "GenericCreateStatusText";
		}


	}
}
