// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.Design
{
	using System.Resources;

	internal class SR
	{
		public static string ExceptionCollectionAlreadyExists
		{
			get { return Keys.GetString( Keys.ExceptionCollectionAlreadyExists ); }
		}
		public static string CategoryFilterSettingsDescription
		{
			get { return Keys.GetString( Keys.CategoryFilterSettingsDescription ); }
		}
		public static string TracingEnabledDescription
		{
			get { return Keys.GetString( Keys.TracingEnabledDescription ); }
		}
		public static string LoggingEnabledDescription
		{
			get { return Keys.GetString( Keys.LoggingEnabledDescription ); }
		}
		public static string DistributionStrategyDescription
		{
			get { return Keys.GetString( Keys.DistributionStrategyDescription ); }
		}
		public static string MsmqPathDescription
		{
			get { return Keys.GetString( Keys.MsmqPathDescription ); }
		}
		public static string MinimumPriority
		{
			get { return Keys.GetString( Keys.MinimumPriority ); }
		}
		public static string InProcDistributionStrategyDescription
		{
			get { return Keys.GetString( Keys.InProcDistributionStrategyDescription ); }
		}
		public static string DistributionStrategyTypeNameDescription
		{
			get { return Keys.GetString( Keys.DistributionStrategyTypeNameDescription ); }
		}
		public static string DistributorServiceNameDescription
		{
			get { return Keys.GetString( Keys.DistributorServiceNameDescription ); }
		}
		public static string DefaultCategoryDescription
		{
			get { return Keys.GetString( Keys.DefaultCategoryDescription ); }
		}
		public static string QueueTimerIntervalDescription
		{
			get { return Keys.GetString( Keys.QueueTimerIntervalDescription ); }
		}
		public static string DefaultFormatDescription
		{
			get { return Keys.GetString( Keys.DefaultFormatDescription ); }
		}
		public static string SinkDescription
		{
			get { return Keys.GetString( Keys.SinkDescription ); }
		}
		public static string FormatDescription
		{
			get { return Keys.GetString( Keys.FormatDescription ); }
		}
		public static string SinkTypeNameDescription
		{
			get { return Keys.GetString( Keys.SinkTypeNameDescription ); }
		}
		public static string FormatterTypeDescription
		{
			get { return Keys.GetString( Keys.FormatterTypeDescription ); }
		}
		public static string CustomFormatterAttributesDescription
		{
			get { return Keys.GetString( Keys.CustomFormatterAttributesDescription ); }
		}
		public static string CustomSinkAttributesDescription
		{
			get { return Keys.GetString( Keys.CustomSinkAttributesDescription ); }
		}
		public static string CustomDistributionStrategyAttributesDescription
		{
			get { return Keys.GetString( Keys.CustomDistributionStrategyAttributesDescription ); }
		}
		public static string EmailSinkToAddressDescription
		{
			get { return Keys.GetString( Keys.EmailSinkToAddressDescription ); }
		}
		public static string EmailSinkFromAddressDescription
		{
			get { return Keys.GetString( Keys.EmailSinkFromAddressDescription ); }
		}
		public static string EmailSinkSubjectLineStarterDescription
		{
			get { return Keys.GetString( Keys.EmailSinkSubjectLineStarterDescription ); }
		}
		public static string EmailSinkSubjectLineEnderDescription
		{
			get { return Keys.GetString( Keys.EmailSinkSubjectLineEnderDescription ); }
		}
		public static string EmailSinkSmtpServerDescription
		{
			get { return Keys.GetString( Keys.EmailSinkSmtpServerDescription ); }
		}
		public static string EventLogSinkEventLogNameDescription
		{
			get { return Keys.GetString( Keys.EventLogSinkEventLogNameDescription ); }
		}
		public static string EventLogSinkEventSourceNameDescription
		{
			get { return Keys.GetString( Keys.EventLogSinkEventSourceNameDescription ); }
		}
		public static string FlatFileSinkFlatFileName
		{
			get { return Keys.GetString( Keys.FlatFileSinkFlatFileName ); }
		}
		public static string FlatFileSinkHeader
		{
			get { return Keys.GetString( Keys.FlatFileSinkHeader ); }
		}
		public static string FlatFileSinkFooter
		{
			get { return Keys.GetString( Keys.FlatFileSinkFooter ); }
		}
      public static string RollingFlatFileSinkFlatFileName
      {
         get { return Keys.GetString( Keys.RollingFlatFileSinkFlatFileName ); }
      }
      public static string RollingFlatFileSinkHeader
      {
         get { return Keys.GetString( Keys.RollingFlatFileSinkHeader ); }
      }
      public static string RollingFlatFileSinkFooter
      {
         get { return Keys.GetString( Keys.RollingFlatFileSinkFooter ); }
      }
      public static string ConsoleSinkHeader
      {
         get { return Keys.GetString( Keys.ConsoleSinkHeader ); }
      }
      public static string ConsoleSinkFooter
      {
         get { return Keys.GetString( Keys.ConsoleSinkFooter ); }
      }
      public static string MsmqSinkQueuePathDescription
		{
			get { return Keys.GetString( Keys.MsmqSinkQueuePathDescription ); }
		}
		public static string MsmqSinkMessagePriorityDescription
		{
			get { return Keys.GetString( Keys.MsmqSinkMessagePriorityDescription ); }
		}
      public static string WSSink
      {
         get { return Keys.GetString( Keys.WSSink ); }
      }
      public static string WSSinkUrl
      {
         get { return Keys.GetString( Keys.WSSinkUrl ); }
      }
		public static string Name
		{
			get { return Keys.GetString( Keys.Name ); }
		}
		public static string LogSettingsNode
		{
			get { return Keys.GetString( Keys.LogSettingsNode ); }
		}
		public static string LogSettingsCmd
		{
			get { return Keys.GetString( Keys.LogSettingsCmd ); }
		}
		public static string ClientSettings
		{
			get { return Keys.GetString( Keys.ClientSettings ); }
		}
		public static string DistributionStrategy
		{
			get { return Keys.GetString( Keys.DistributionStrategy ); }
		}
		public static string DistributionStrategies
		{
			get { return Keys.GetString( Keys.DistributionStrategies ); }
		}
		public static string CustomDistributionStrategy
		{
			get { return Keys.GetString( Keys.CustomDistributionStrategy ); }
		}
		public static string MsmqDistributionStrategy
		{
			get { return Keys.GetString( Keys.MsmqDistributionStrategy ); }
		}
		public static string InProcDistributionStrategy
		{
			get { return Keys.GetString( Keys.InProcDistributionStrategy ); }
		}
		public static string DistributorSettings
		{
			get { return Keys.GetString( Keys.DistributorSettings ); }
		}
		public static string Sinks
		{
			get { return Keys.GetString( Keys.Sinks ); }
		}
		public static string Sink
		{
			get { return Keys.GetString( Keys.Sink ); }
		}
		public static string CustomSink
		{
			get { return Keys.GetString( Keys.CustomSink ); }
		}
		public static string DatabaseSink
		{
			get { return Keys.GetString( Keys.DatabaseSink ); }
		}
		public static string EmailSink
		{
			get { return Keys.GetString( Keys.EmailSink ); }
		}
		public static string EventLogSink
		{
			get { return Keys.GetString( Keys.EventLogSink ); }
		}
		public static string FlatFileSink
		{
			get { return Keys.GetString( Keys.FlatFileSink ); }
		}
      public static string RollingFlatFileSink
      {
         get { return Keys.GetString( Keys.RollingFlatFileSink ); }
      }
      public static string ConsoleSink
      {
         get { return Keys.GetString( Keys.ConsoleSink ); }
      }
		public static string MsmqSink
		{
			get { return Keys.GetString( Keys.MsmqSink ); }
		}
		public static string WmiLogSink
		{
			get { return Keys.GetString( Keys.WmiLogSink ); }
		}
		public static string Formatters
		{
			get { return Keys.GetString( Keys.Formatters ); }
		}
		public static string Formatter
		{
			get { return Keys.GetString( Keys.Formatter ); }
		}
		public static string Categories
		{
			get { return Keys.GetString( Keys.Categories ); }
		}
		public static string Category
		{
			get { return Keys.GetString( Keys.Category ); }
		}
		public static string CustomFormatter
		{
			get { return Keys.GetString( Keys.CustomFormatter ); }
		}
		public static string TextFormatter
		{
			get { return Keys.GetString( Keys.TextFormatter ); }
		}
		public static string Destinations
		{
			get { return Keys.GetString( Keys.Destinations ); }
		}
		public static string Destination
		{
			get { return Keys.GetString( Keys.Destination ); }
		}
		public static string DistributorService
		{
			get { return Keys.GetString( Keys.DistributorService ); }
		}
		public static string TemplatePlaceHolder
		{
			get { return Keys.GetString( Keys.TemplatePlaceHolder ); }
		}
		public static string CategoryFilterSummaryAllow
		{
			get { return Keys.GetString( Keys.CategoryFilterSummaryAllow ); }
		}
		public static string CategoryFilterSummaryDeny
		{
			get { return Keys.GetString( Keys.CategoryFilterSummaryDeny ); }
		}
		public static string DefaultFormatter
		{
			get { return Keys.GetString( Keys.DefaultFormatter ); }
		}
		public static string DefaultFormatterDescription
		{
			get { return Keys.GetString( Keys.DefaultFormatterDescription ); }
		}
		public static string DefaultCategory
		{
			get { return Keys.GetString( Keys.DefaultCategory ); }
		}
		public static string DefaultCategoryDestination
		{
			get { return Keys.GetString( Keys.DefaultCategoryDestination ); }
		}
		public static string DefaultTracingCategory
		{
			get { return Keys.GetString( Keys.DefaultTracingCategory ); }
		}
		public static string DefaultTracingFileSink
		{
			get { return Keys.GetString( Keys.DefaultTracingFileSink ); }
		}
		public static string DefaultTracingDestination
		{
			get { return Keys.GetString( Keys.DefaultTracingDestination ); }
		}
		public static string DefaultTextFormat
		{
			get { return Keys.GetString( Keys.DefaultTextFormat ); }
		}
		public static string GenericCreateStatusText (string name)
		{
			return Keys.GetString( Keys.GenericCreateStatusText, name );
		}
		public static string CategoryGeneral
		{
			get { return Keys.GetString( Keys.CategoryGeneral ); }
		}
		public static string DuplicateSinkInDestationMessage (string destinationName, string sinkName)
		{
			return Keys.GetString( Keys.DuplicateSinkInDestationMessage, destinationName, sinkName );
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.Design.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Logging.Configuration.Design.SR).Module.Assembly );

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, Resources.UICultureInfo );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, Resources.UICultureInfo );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string ExceptionCollectionAlreadyExists = "ExceptionCollectionAlreadyExists";
			public const string CategoryFilterSettingsDescription = "CategoryFilterSettingsDescription";
			public const string TracingEnabledDescription = "TracingEnabledDescription";
			public const string LoggingEnabledDescription = "LoggingEnabledDescription";
			public const string DistributionStrategyDescription = "DistributionStrategyDescription";
			public const string MsmqPathDescription = "MsmqPathDescription";
			public const string MinimumPriority = "MinimumPriority";
			public const string InProcDistributionStrategyDescription = "InProcDistributionStrategyDescription";
			public const string DistributionStrategyTypeNameDescription = "DistributionStrategyTypeNameDescription";
			public const string DistributorServiceNameDescription = "DistributorServiceNameDescription";
			public const string DefaultCategoryDescription = "DefaultCategoryDescription";
			public const string QueueTimerIntervalDescription = "QueueTimerIntervalDescription";
			public const string DefaultFormatDescription = "DefaultFormatDescription";
			public const string SinkDescription = "SinkDescription";
			public const string FormatDescription = "FormatDescription";
			public const string SinkTypeNameDescription = "SinkTypeNameDescription";
			public const string FormatterTypeDescription = "FormatterTypeDescription";
			public const string CustomFormatterAttributesDescription = "CustomFormatterAttributesDescription";
			public const string CustomSinkAttributesDescription = "CustomSinkAttributesDescription";
			public const string CustomDistributionStrategyAttributesDescription = "CustomDistributionStrategyAttributesDescription";
			public const string EmailSinkToAddressDescription = "EmailSinkToAddressDescription";
			public const string EmailSinkFromAddressDescription = "EmailSinkFromAddressDescription";
			public const string EmailSinkSubjectLineStarterDescription = "EmailSinkSubjectLineStarterDescription";
			public const string EmailSinkSubjectLineEnderDescription = "EmailSinkSubjectLineEnderDescription";
			public const string EmailSinkSmtpServerDescription = "EmailSinkSmtpServerDescription";
			public const string EventLogSinkEventLogNameDescription = "EventLogSinkEventLogNameDescription";
			public const string EventLogSinkEventSourceNameDescription = "EventLogSinkEventSourceNameDescription";
			public const string FlatFileSinkFlatFileName = "FlatFileSinkFlatFileName";
			public const string FlatFileSinkHeader = "FlatFileSinkHeader";
			public const string FlatFileSinkFooter = "FlatFileSinkFooter";
         public const string RollingFlatFileSinkFlatFileName = "RollingFlatFileSinkFlatFileName";
         public const string RollingFlatFileSinkHeader = "RollingFlatFileSinkHeader";
         public const string RollingFlatFileSinkFooter = "RollingFlatFileSinkFooter";
         public const string OneFilePerWeekDay = "OneFilePerWeekDay";
         public const string RolloverByMinutes = "RolloverByMinutes";
         public const string RolloverByDays = "RolloverByDays";
         public const string RolloverByMegabytes = "RolloverByMegabytes";
         public const string NumFilesToKeep = "NumFilesToKeep";
         public const string ConsoleSinkHeader = "ConsoleSinkHeader";
         public const string ConsoleSinkFooter = "ConsoleSinkFooter";
         public const string MsmqSinkQueuePathDescription = "MsmqSinkQueuePathDescription";
			public const string MsmqSinkMessagePriorityDescription = "MsmqSinkMessagePriorityDescription";
			public const string Name = "Name";
			public const string LogSettingsNode = "LogSettingsNode";
			public const string LogSettingsCmd = "LogSettingsCmd";
			public const string ClientSettings = "ClientSettings";
			public const string DistributionStrategy = "DistributionStrategy";
			public const string DistributionStrategies = "DistributionStrategies";
			public const string CustomDistributionStrategy = "CustomDistributionStrategy";
			public const string MsmqDistributionStrategy = "MsmqDistributionStrategy";
			public const string InProcDistributionStrategy = "InProcDistributionStrategy";
			public const string DistributorSettings = "DistributorSettings";
			public const string Sinks = "Sinks";
			public const string Sink = "Sink";
			public const string CustomSink = "CustomSink";
			public const string DatabaseSink = "DatabaseSink";
			public const string EmailSink = "EmailSink";
			public const string EventLogSink = "EventLogSink";
			public const string FlatFileSink = "FlatFileSink";
         public const string RollingFlatFileSink = "RollingFlatFileSink";
         public const string ConsoleSink = "ConsoleSink";
			public const string MsmqSink = "MsmqSink";
			public const string WmiLogSink = "WmiLogSink";
         public const string WSSink = "WSSink";
         public const string WSSinkUrl = "WSSinkUrl";
			public const string Formatters = "Formatters";
			public const string Formatter = "Formatter";
			public const string Categories = "Categories";
			public const string Category = "Category";
			public const string CustomFormatter = "CustomFormatter";
			public const string TextFormatter = "TextFormatter";
			public const string Destinations = "Destinations";
			public const string Destination = "Destination";
			public const string DistributorService = "DistributorService";
			public const string TemplatePlaceHolder = "TemplatePlaceHolder";
			public const string CategoryFilterSummaryAllow = "CategoryFilterSummaryAllow";
			public const string CategoryFilterSummaryDeny = "CategoryFilterSummaryDeny";
			public const string DefaultFormatter = "DefaultFormatter";
			public const string DefaultFormatterDescription = "DefaultFormatterDescription";
			public const string DefaultCategory = "DefaultCategory";
			public const string DefaultCategoryDestination = "DefaultCategoryDestination";
			public const string DefaultTracingCategory = "DefaultTracingCategory";
			public const string DefaultTracingFileSink = "DefaultTracingFileSink";
			public const string DefaultTracingDestination = "DefaultTracingDestination";
			public const string DefaultTextFormat = "DefaultTextFormat";
			public const string GenericCreateStatusText = "GenericCreateStatusText";
			public const string CategoryGeneral = "CategoryGeneral";
         public const string CategorySpecial = "CategorySpecial";
         public const string CategoryRollover = "CategoryRollover";
			public const string DuplicateSinkInDestationMessage = "DuplicateSinkInDestationMessage";
		}


	}
}
