using System.Resources;
// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//

namespace Microsoft.Practices.EnterpriseLibrary.Security.ActiveDirectory
{
    internal class SR
    {
        public static string ADAuthorizationProviderConfigDataNull
        {
            get { return Keys.GetString(Keys.ADAuthorizationProviderConfigDataNull); }
        }

        public static string ADAuthorizationProviderConfigDataInvalid
        {
            get { return Keys.GetString(Keys.ADAuthorizationProviderConfigDataInvalid); }
        }

        internal class Keys
        {
            private static ResourceManager resourceManager =
                new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.ActiveDirectory.SR", typeof(SR).Module.Assembly);

            public static string GetString(string key)
            {
                return resourceManager.GetString(key, Resources.CultureInfo);
            }

            public static string GetString(string key, params object[] args)
            {
                string msg = resourceManager.GetString(key, Resources.CultureInfo);
                msg = string.Format(msg, args);
                return msg;
            }

            public const string ADAuthorizationProviderConfigDataNull = "ADAuthorizationProviderConfigDataNull";
            public const string ADAuthorizationProviderConfigDataInvalid = "ADAuthorizationProviderConfigDataInvalid";
        }

    }
}