// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Security.Cache.CachingStore.Configuration.Design
{
	using System;
	using System.Resources;
	using System.Globalization;

	internal class SR
	{
		public static string SecurityInstance
		{
			get { return Keys.GetString( Keys.SecurityInstance ); }
		}
		public static string DefaultCacheManager
		{
			get { return Keys.GetString( Keys.DefaultCacheManager ); }
		}
		public static string AbsoluteExpirationDescription
		{
			get { return Keys.GetString( Keys.AbsoluteExpirationDescription ); }
		}
		public static string SlidingExpirationDescription
		{
			get { return Keys.GetString( Keys.SlidingExpirationDescription ); }
		}
		public static string CacheInstanceDescription
		{
			get { return Keys.GetString( Keys.CacheInstanceDescription ); }
		}
		public static string DefaultSecurityCacheDescription
		{
			get { return Keys.GetString( Keys.DefaultSecurityCacheDescription ); }
		}
		public static string CategoryGeneral
		{
			get { return Keys.GetString( Keys.CategoryGeneral ); }
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.Cache.CachingStore.Configuration.Design.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Security.Cache.CachingStore.Configuration.Design.SR).Module.Assembly );

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, Resources.CultureInfo );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, Resources.CultureInfo );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string SecurityInstance = "SecurityInstance";
			public const string DefaultCacheManager = "DefaultCacheManager";
			public const string AbsoluteExpirationDescription = "AbsoluteExpirationDescription";
			public const string SlidingExpirationDescription = "SlidingExpirationDescription";
			public const string CacheInstanceDescription = "CacheInstanceDescription";
			public const string DefaultSecurityCacheDescription = "DefaultSecurityCacheDescription";
			public const string CategoryGeneral = "CategoryGeneral";
		}


	}
}
