using System.Globalization;
using System.Resources;
// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//

namespace Microsoft.Practices.EnterpriseLibrary.Security.Database.Authentication
{
    internal class SR
    {
        public static CultureInfo Culture
        {
            get { return Keys.Culture; }
            set { Keys.Culture = value; }
        }

        public static string DBAuthenticationProviderConfigDataIsNull
        {
            get { return Keys.GetString(Keys.DBAuthenticationProviderConfigDataIsNull); }
        }

        public static string DBAuthenticationProviderConfigDataInvalid
        {
            get { return Keys.GetString(Keys.DBAuthenticationProviderConfigDataInvalid); }
        }

        public static string NamePasswordCredentialsAreNull
        {
            get { return Keys.GetString(Keys.NamePasswordCredentialsAreNull); }
        }

        public static string NamePasswordCredentialsInvalid
        {
            get { return Keys.GetString(Keys.NamePasswordCredentialsInvalid); }
        }

        internal class Keys
        {
            private static ResourceManager resourceManager =
                new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.Database.Authentication.SR", typeof(SR).Module.Assembly);

            private static CultureInfo culture = null;

            public static CultureInfo Culture
            {
                get { return culture; }
                set { culture = value; }
            }

            public static string GetString(string key)
            {
                return resourceManager.GetString(key, culture);
            }

            public static string GetString(string key, params object[] args)
            {
                string msg = resourceManager.GetString(key, culture);
                msg = string.Format(msg, args);
                return msg;
            }

            public const string DBAuthenticationProviderConfigDataIsNull = "DBAuthenticationProviderConfigDataIsNull";
            public const string DBAuthenticationProviderConfigDataInvalid = "DBAuthenticationProviderConfigDataInvalid";
            public const string NamePasswordCredentialsAreNull = "NamePasswordCredentialsAreNull";
            public const string NamePasswordCredentialsInvalid = "NamePasswordCredentialsInvalid";
        }

    }
}