using System.Resources;
// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//

namespace Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging
{
    internal class SR
    {
        public static string MissingConstructor(string formatterName)
        {
            return Keys.GetString(Keys.MissingConstructor, formatterName);
        }

        internal class Keys
        {
            private static ResourceManager resourceManager =
                new ResourceManager("Microsoft.Practices.EnterpriseLibrary.ExceptionHandling.Logging.SR", typeof(SR).Module.Assembly);

            public static string GetString(string key)
            {
                return resourceManager.GetString(key, Resources.CultureInfo);
            }

            public static string GetString(string key, params object[] args)
            {
                string msg = resourceManager.GetString(key, Resources.CultureInfo);
                msg = string.Format(msg, args);
                return msg;
            }

            public const string MissingConstructor = "MissingConstructor";
        }

    }
}