//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 
namespace Microsoft.Practices.EnterpriseLibrary.Logging.webservice {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LoggingSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[][]))]
    public class Logging : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Logging() {
            this.Url = "http://localhost/Webservice1/service1.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Log", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Log([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] WSLogEntry logEntry) {
            this.Invoke("Log", new object[] {
                        logEntry});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLog(WSLogEntry logEntry, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Log", new object[] {
                        logEntry}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndLog(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public class WSLogEntry {
        
        /// <remarks/>
        public string Message;
        
        /// <remarks/>
        public string Category;
        
        /// <remarks/>
        public int Priority;
        
        /// <remarks/>
        public int EventId;
        
        /// <remarks/>
        public Severity Severity;
        
        /// <remarks/>
        public int LoggedSeverity;
        
        /// <remarks/>
        public string Title;
        
        /// <remarks/>
        public System.DateTime TimeStamp;
        
        /// <remarks/>
        public string MachineName;
        
        /// <remarks/>
        public string AppDomainName;
        
        /// <remarks/>
        public string ProcessId;
        
        /// <remarks/>
        public string ProcessName;
        
        /// <remarks/>
        public string ManagedThreadName;
        
        /// <remarks/>
        public string Win32ThreadId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public object[][] ExtendedProperties;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum Severity {
        
        /// <remarks/>
        Unspecified,
        
        /// <remarks/>
        Information,
        
        /// <remarks/>
        Warning,
        
        /// <remarks/>
        Error,
    }
}
