// WARNING:
// This file generated by the Microsoft DataWarehouse String Resource Tool 1.13.5000.0
// from information in SR.strings.   
// DO NO MODIFY THIS FILE'S CONTENTS, THEY WILL BE OVERWRITTEN
//
namespace Microsoft.Practices.EnterpriseLibrary.Security.ActiveDirectory.Configuration.Design
{
	using System;
	using System.Resources;
	using System.Globalization;

	internal class SR
	{
		public static string ActiveDirectoryRolesProviderDisplayName
		{
			get { return Keys.GetString( Keys.ActiveDirectoryRolesProviderDisplayName ); }
		}
		public static string ProviderTypePropertyDescription
		{
			get { return Keys.GetString( Keys.ProviderTypePropertyDescription ); }
		}
		public static string ServerPropertyDescription
		{
			get { return Keys.GetString( Keys.ServerPropertyDescription ); }
		}
		public static string UserPartitionPropertyDescription
		{
			get { return Keys.GetString( Keys.UserPartitionPropertyDescription ); }
		}
		public static string AccountNamePropertyDescription
		{
			get { return Keys.GetString( Keys.AccountNamePropertyDescription ); }
		}
		public static string ActiveDirectoryProvider
		{
			get { return Keys.GetString( Keys.ActiveDirectoryProvider ); }
		}
		public static string AccountNameFieldName
		{
			get { return Keys.GetString( Keys.AccountNameFieldName ); }
		}

		internal class Keys 
		{
			static ResourceManager resourceManager = 
				new ResourceManager("Microsoft.Practices.EnterpriseLibrary.Security.ActiveDirectory.Configuration.Design.SR", typeof(Microsoft.Practices.EnterpriseLibrary.Security.ActiveDirectory.Configuration.Design.SR).Module.Assembly );

			public static string GetString( string key )
			{
				return resourceManager.GetString( key, Resources.CultureInfo );
			}
			public static string GetString( string key, params object[] args )
			{
				string msg = resourceManager.GetString( key, Resources.CultureInfo );
				msg = string.Format( msg, args );
				return msg;
			}

			public const string ActiveDirectoryRolesProviderDisplayName = "ActiveDirectoryRolesProviderDisplayName";
			public const string ProviderTypePropertyDescription = "ProviderTypePropertyDescription";
			public const string ServerPropertyDescription = "ServerPropertyDescription";
			public const string UserPartitionPropertyDescription = "UserPartitionPropertyDescription";
			public const string AccountNamePropertyDescription = "AccountNamePropertyDescription";
			public const string ActiveDirectoryProvider = "ActiveDirectoryProvider";
			public const string AccountNameFieldName = "AccountNameFieldName";
		}


	}
}
